package com.github.matiasvergaras.finalreality.model.character.player.Normal;

import com.github.matiasvergaras.finalreality.model.character.ICharacter;
import com.github.matiasvergaras.finalreality.model.weapon.Magic.Staff;
import com.github.matiasvergaras.finalreality.model.weapon.Normal.Axe;
import com.github.matiasvergaras.finalreality.model.weapon.Normal.Knife;
import com.github.matiasvergaras.finalreality.model.weapon.Normal.Sword;
import org.jetbrains.annotations.NotNull;

import java.util.Objects;
import java.util.concurrent.BlockingQueue;

/**
 * Class to represent a ''Knight'' unit.
 * <p>
 *Knights can equip Swords, Axes and Knives, and cannot use magic spells.
 *
 * @author Matías Vergara Silva
 *
 */
public class Knight extends AbstractNormalCharacter{
    /**

     * Creates a new Knight Character
     * @param turnsQueue
     *     the queue with the characters ready to play
     * @param name
     *     the character's name
     * @param HP
     *     the character's heal points
     * @param DP
     *     the character's defense points
     */
    public Knight(@NotNull BlockingQueue<ICharacter> turnsQueue,
                  @NotNull String name, int HP, int DP) {
        super(turnsQueue, name, "KNIGHT", HP, DP);
    }


    /**
     * Equips a Sword to this character
     * @param weapon
     *        the Sword to equip
     */
    public void equip(Sword weapon) {
        super.equip(weapon);
    }

    /**
     * Equips an Axe to this character
     * @param weapon
     *        the Axe to equip
     */
    public void equip(Axe weapon) {
        super.equip(weapon);
    }

    /**
     * Equips an  Knife to this character
     * @param weapon
     *        the e Knife to equip
     */
    public void equip(Knife weapon) {
        super.equip(weapon);
    }





    /**
     * Check if this is equal to a given object o.
     * @param o The target object
     * @return True if are equals, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Knight)) return false;
        Knight that = (Knight) o;
        return this.getCharacterClass().equals(that.getCharacterClass()) &&
                this.getName().equals(that.getName()) &&
                this.getHP()==that.getHP() &&
                this.getDP()==that.getDP();
    }

    /**
     * Returns an integer value, generated by a hashing algorithm, distinct
     * for distinct objects. Required for the equals method.
     * @return Integer hash code.
     */
    @Override
    public int hashCode() {
        return Objects.hash( this.getName() +
                this.getCharacterClass());
    }

}
