package com.github.matiasvergaras.finalreality.model.weapon.Normal;

import com.github.matiasvergaras.finalreality.model.character.player.IPlayerCharacter;

import java.util.Objects;

/**
 * Class to represent a ''Bow'' weapon.
 * <p>
 *
 *
 * @author Matías Vergara Silva
 *
 */


public class Bow extends AbstractNormalWeapon{
    /**
     * Creates a Bow object with a name, a base damage, weight and type.
     * @param name
     *              the Bow name
     * @param power
     *              the Bow power
     * @param weight
     *              the Bow weight
     */
    public Bow(final String name, final int power, final int weight) {
        super(name, power, weight);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void equipTo(IPlayerCharacter character) {
        character.equipBow(this);
        super.setOwner(character);
    }


    /**
     * Check if this is equal to a given object o.
     * @param o The target object
     * @return True if are equals, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Bow)) return false;
        Bow that = (Bow) o;
        return this.getName().equals(that.getName()) &&
                this.getPower() == that.getPower() &&
                this.getWeight() == that.getWeight();
    }

    /**
     * Returns an integer value, generated by a hashing algorithm, distinct
     * for distinct objects. Required for the equals method.
     * @return Integer hash code.
     */
    @Override
    public int hashCode() {
        return Objects.hash(this.getName(), this.getPower(),
                this.getWeight());
    }

}
