package com.github.matiasvergaras.finalreality.model.weapon.Normal;

import com.github.matiasvergaras.finalreality.model.character.player.IPlayerCharacter;
import com.github.matiasvergaras.finalreality.model.weapon.AbstractWeapon;

import java.util.Objects;

/**
 * Class to represent a ''Knife'' weapon.
 * <p>
 * Knives (Knife) can be used by Knights, Engineers and Thieves (Thief).
 *
 * @author Matías Vergara Silva
 *
 */

public class Knife extends AbstractWeapon {

    /**
     * Creates a Knife object with a name, a base damage, weight and type.
     * @param name
     *              the Knife name
     * @param power
     *              the Knife power
     * @param weight
     *              the Knife weight
     */
    public Knife(final String name, final int power, final int weight) {
        super(name, power, weight);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void equipToKnight(IPlayerCharacter character) {
        character.equip(this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void equipToBlackMage(IPlayerCharacter character) {
        setWeaponFree();
        character.equip(this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void equipToThief(IPlayerCharacter character) {
        setWeaponFree();
        character.equip(this);
    }

    /**
     * Check if this is equal to a given object o.
     * @param o The target object
     * @return True if are equals, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Knife)) return false;
        Knife that = (Knife) o;
        return this.getName().equals(that.getName()) &&
                this.getPower() == that.getPower() &&
                this.getWeight() == that.getWeight();
    }

    /**
     * Returns an integer value, generated by a hashing algorithm, distinct
     * for distinct objects. Required for the equals method.
     * @return Integer hash code.
     */
    @Override
    public int hashCode() {
        return Objects.hash(this.getName(), this.getPower(),
                this.getWeight());
    }

}
