package com.github.matiasvergaras.finalreality.model.weapon.Normal;

import com.github.matiasvergaras.finalreality.model.character.player.IPlayerCharacter;

import java.util.Objects;

public class NullWeapon extends AbstractNormalWeapon {

    /**
     * Constructor for a default normal weapon without any special behaviour.
     */
    public NullWeapon() {
        super("", 0, 0);
    }

    @Override
    public void equipTo(IPlayerCharacter character) {
        character.equip(this);
        super.setOwner(character);
    }

    /**
     * Check if this is equal to a given object o.
     * @param o The target object
     * @return True if are equals, false otherwise
     */
    @Override
    public boolean equals(Object o){
        if (this == o) return true;
        if (!(o instanceof NullWeapon)) return false;
        NullWeapon that = (NullWeapon) o;
        return this.getPower() == that.getPower() &&
                this.getWeight() == that.getWeight() &&
                getName().equals(that.getName());
    }

    /**
     * Returns an integer value, generated by a hashing algorithm, distinct
     * for distinct objects. Required for the equals method.
     * @return Integer hash code.
     */
    @Override
    public int hashCode() {
        return Objects.hash(this.getName(), this.getPower(),
                this.getWeight());
    }

}
