package com.github.matiasvergaras.finalreality.model.Mastermind;

import com.github.matiasvergaras.finalreality.model.character.ICharacter;


import java.util.ArrayList;
import java.util.Objects;

/**
 * A class to hold all the behavior of a CPUMastermind
 * <p> Since the party is of the CPU and not of the Controller, we decided to create this class to hold it. </p>
 * <p> The name of the CPU Mastermind will be used to identify different game-levels or difficulty. </p>
 */
public class CPUMastermind extends AbstractMastermind {

    /**
     * Constructor of a new CPUPMastermind.
     * It assigns a new empty party to this CPUMastermind.
     */
    public CPUMastermind(String name){
        super(name);
    }

    /**
     * Check if this is equal to a given object o.
     *
     * @param o The target object
     * @return True if are equals, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CPUMastermind)) return false;
        CPUMastermind that = (CPUMastermind) o;
        return this.getName().equals(that.getName());
    }

    /**
     * Returns an integer value, generated by a hashing algorithm, distinct
     * for distinct objects. Required for the equals method.
     *
     * @return Integer hash code.
     */
    @Override
    public int hashCode() {
        return Objects.hash(this.getName());
    }

}
